"""`recon ops lineage`: `dbt docs generate` + a markdown lineage summary from manifest.json.

The dbt docs site (index.html, manifest.json, catalog.json) goes to `data/.dbt/lineage/target`
(git-ignored). The summary goes to `reports/lineage/LINEAGE.md`. It has no timestamps, so two
runs give the same file. The catalog is empty (`--empty-catalog`): no DB is opened or changed.
"""

import json
import shutil
from collections.abc import Mapping
from pathlib import Path

from casarecon.core import paths
from casarecon.core.config import dbt_vars
from casarecon.core.deps import get_dbt_runner
from casarecon.core.errors import CasaReconError
from casarecon.ports import DbtRunner

KEEP = ("model", "seed")


def _short(node_id: str) -> str:
    """'model.casarecon.stg_fx' -> 'stg_fx'; 'source.casarecon.raw.transactions' -> 'raw.transactions'."""
    parts = node_id.split(".")
    return ".".join(parts[2:]) if parts[0] == "source" else parts[-1]


def summarize(manifest: Mapping) -> list[dict]:
    """One row per model: layer, materialization, direct parents and all upstream sources/seeds."""
    nodes = {k: v for k, v in manifest["nodes"].items() if v["resource_type"] in KEEP}
    parents = {k: v.get("depends_on", {}).get("nodes", []) for k, v in nodes.items()}

    def roots(node_id: str) -> set[str]:
        if not node_id.startswith("model."):
            return {node_id}
        return {r for p in parents.get(node_id, []) for r in roots(p)}

    return sorted(({"model": v["name"], "layer": v["schema"],
                    "materialized": v.get("config", {}).get("materialized", ""),
                    "parents": sorted(_short(p) for p in parents[k]),
                    "sources": sorted(_short(r) for r in roots(k))}
                   for k, v in nodes.items() if v["resource_type"] == "model"),
                  key=lambda r: (r["layer"], r["model"]))


def to_markdown(rows: list[dict], docs_dir: Path) -> str:
    """Table + mermaid graph. Deterministic (no timestamps)."""
    lines = ["# dbt lineage", "", "Generated by `recon ops lineage` from dbt `manifest.json`.",
             f"Full docs site: `{docs_dir}` (serve it with `python -m http.server` from that folder).", "",
             "| Model | Layer | Materialized | Parents | Upstream sources / seeds |", "|---|---|---|---|---|"]
    lines += [f"| `{r['model']}` | {r['layer']} | {r['materialized']} | {', '.join(r['parents'])} "
              f"| {', '.join(r['sources'])} |" for r in rows]
    edges = sorted({(p, r["model"]) for r in rows for p in r["parents"]})
    lines += ["", "```mermaid", "graph LR", *[f"  {a.replace('.', '_')}[{a}] --> {b}" for a, b in edges], "```", ""]
    return "\n".join(lines)


def generate_docs(work: Path, runner: DbtRunner) -> Path:
    """Run `dbt docs generate` into work/target against a throwaway DuckDB file."""
    args = ["docs", "generate", "--empty-catalog", "--vars", dbt_vars(),
            "--target-path", str(work / "target"), "--log-path", str(work / "logs")]
    env = {"CASARECON_BUILD_PATH": str(work / "lineage.duckdb"), "CASARECON_RAW_DIR": str(paths.raw_dir())}
    code = runner(args, env)
    (work / "lineage.duckdb").unlink(missing_ok=True)
    if code != 0:
        raise CasaReconError(f"dbt docs generate failed (exit {code})")
    return work / "target"


def main(*, runner: DbtRunner | None = None, out: Path | None = None) -> dict:
    """Write reports/lineage/LINEAGE.md. Returns {'summary': path, 'docs': path, 'models': n}."""
    work = paths.db_path().parent / ".dbt" / "lineage"
    shutil.rmtree(work / "target", ignore_errors=True)
    target = generate_docs(work, runner or get_dbt_runner())
    rows = summarize(json.loads((target / "manifest.json").read_text()))
    out_file = out or paths.reports_dir() / "lineage" / "LINEAGE.md"
    out_file.parent.mkdir(parents=True, exist_ok=True)
    rel = target.relative_to(paths.REPO_ROOT) if target.is_relative_to(paths.REPO_ROOT) else target
    out_file.write_text(to_markdown(rows, rel))
    return {"summary": str(out_file), "docs": str(target), "models": len(rows)}
